spring.application.name=HuechurabaBMW

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/VH2_Vehiculos
spring.datasource.username=root
spring.datasource.password=PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none 

spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration